name: Build & Publish to Dynamis

on:
  push:
    tags:
      - "v*.*.*.*"

jobs:
  Build:
    runs-on: windows-latest
   
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Get Tag Name
        run: |
          VERSION=${{ github.event.release.tag_name }}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Download Dalamud Latest
        run: |
          Invoke-WebRequest -Uri https://goatcorp.github.io/dalamud-distrib/latest.zip -OutFile latest.zip
          Expand-Archive -Force latest.zip "$env:AppData\XIVLauncher\addon\Hooks\dev\"

      - name: Restore Project
        run: dotnet restore

      - name: Build Project
        run: dotnet build --configuration Release AutoHook/AutoHook.csproj -p:AssemblyVersion=$VERSION

      - name: Publish Version
        uses: PunishXIV/dynamis-action@v1
        id: dynamis
        with:
          plugin_id: 47
          internal_name: "AutoHook"
          version_number: $VERSION
          path: "AutoHook/bin/Release/AutoHook/latest.zip"
          type: "latest"
          dalamud_version: "9"
        env:
          PUBLISHER_KEY: ${{ secrets.PUBLISHER_KEY }}